### ISSUE TITLE
[Bug]: Admin bar isn't visible when using a independent authentication guard

### ISSUE THREAD

**Issue by justkidding96** [el-schneider/statamic-admin-bar#7]
### What happened?

When using a independent authentication guard the admin bar isn't visible. See https://statamic.dev/tips/using-an-independent-authentication-guard for information.

### How to reproduce the bug

Install a new Statamic site with admin bar addon installed. Then configure a independent authentication guard see: https://statamic.dev/tips/using-an-independent-authentication-guard how you can do this. Then test the admin bar.

### Environment

```yaml
Environment
Application Name:-
Laravel Version: 11.44.0
PHP Version: 8.3.17
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: -
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.49.0 PRO

Statamic Addons
el-schneider/statamic-admin-bar: 0.2.0
withcandour/aardvark-seo: 5.0.1
```
